# Generated by Django 5.2.3 on 2025-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("guests", models.IntegerField()),
            ],
        ),
    ]
